### PR TITLE
Updating FindArnold.cmake

### PR DESCRIPTION
**Pull request by sirpalee**
Updating FindArnold.cmake. The following features were added.
- Applications supplied by Arnold are now stored in variables.
- When building the version string, it's easy to access sub-versions. (Arch, Major, Minor, Bugfix)
- Adding a function to compile .osl files to .oso using the Arnold supplied oslc, and installing them easily.

### CODE REVIEW

**Comment by chadrik** [comment]
Don't change the style for local and input variables. Those were chosen based on research into official cmake modules and there was some effort made to standardize all of the modules in this repo based on those conventions. In particular, all variables in cmake are global so prefixing local variables with the app name is good practice to avoid tricky bugs.

**Comment by sirpalee** [comment]
@chadrik Thanks for the feedback! I updated the pull request with renaming all the temporary variables, and prefixing with _arnold_.

**Comment by chadrik** [comment]
@sirpalee Sorry I let this linger.  Can you address the remaining two notes and I'll get it merged.

**Comment by chadrik** [comment]
@sirpalee Sorry I let this linger.  Can you address the remaining two notes and I'll get it merged.

**Comment by sirpalee** [comment]
@chadrik run through the style guide and made sure everything matches. Also added support for Arnold_HOME, (since the style guide prefers variables like that) but kept the old one for backward compatibility.

**Pull request closed without merging**
